---
baseurl: /bistro
url: http://facebook.github.io
permalink: /blog/:year/:month/:day/:title.html
name: Bistro
relative_permalinks: false
description: XXX
paginate: 5
paginate_path: /blog/page:num/
timezone: America/Los_Angeles

safe: true  # disable custom plugins, ignore symlinks
lsi: false  # don't index related posts, it's probably not great for us

markdown: kramdown
highlighter: pygments
